version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /fce-extension
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /tools/tee-signer
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
